### ISSUE TITLE
Keyboard input

### ISSUE THREAD

**Issue by Tuqz** [Tuqz/athelia#1] opened 2015-02-23 16:57 UTC
The 'block' techdemo fails to respond to user input.

**Comment by jacob-hartmann** [comment] 2015-02-23 18:59
I can confirmed this on Windows 7. I am working on getting debug symbols built in an attempt to track this down.

**Comment by Jacob843** [comment] 2015-02-25 19:59
Tuqz, I just noticed that both techdemos/block/main.cpp and techdemos/template/main.cpp have main() functions. One calls OIS while one doesn't. On my system, scons seems to be compiling template's main (the log name is "LOG_NAME", which matches up locally), when it should be compiling block's main. This should be fixed. Additionally, note that I have created the nightly branch, where I will be pushing most of my changes.

**Comment by jacob-hartmann** [comment] 2015-02-25 22:58
OIS works in Nightly build 5f76d5e  If you want Tuqz, you can close this.

**Comment by jacob-hartmann** [comment] 2015-02-27 22:35
Since there has been no response to this issue within a few days, and it is confirmed fixed in the Nightly, I am closing this issue.

**Closed as completed by jacob-hartmann** 2015-02-27 22:35 UTC
Labels: bug
